name: Scan secrets
description: Scan the repository for hard-coded secrets
runs:
  using: composite
  steps:
    - name: Scan repository history
      shell: bash
      run: ALL_FILES=true ./scripts/githooks/scan-secrets.sh